USE [master]
GO
/****** Object:  Database [GreenGarden]    Script Date: 6/3/2022 2:40:09 PM ******/
CREATE DATABASE [GreenGarden]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreenGarden', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GreenGarden.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GreenGarden_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GreenGarden_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GreenGarden] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreenGarden].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GreenGarden] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GreenGarden] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GreenGarden] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GreenGarden] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GreenGarden] SET ARITHABORT OFF 
GO
ALTER DATABASE [GreenGarden] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GreenGarden] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GreenGarden] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GreenGarden] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GreenGarden] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GreenGarden] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GreenGarden] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GreenGarden] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GreenGarden] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GreenGarden] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GreenGarden] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GreenGarden] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GreenGarden] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GreenGarden] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GreenGarden] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GreenGarden] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GreenGarden] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GreenGarden] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GreenGarden] SET  MULTI_USER 
GO
ALTER DATABASE [GreenGarden] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GreenGarden] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GreenGarden] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GreenGarden] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GreenGarden] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GreenGarden] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GreenGarden] SET QUERY_STORE = OFF
GO
USE [GreenGarden]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 6/3/2022 2:40:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[Account_id] [nvarchar](50) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[PhoneNumber] [nvarchar](50) NOT NULL,
	[AccountType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Account_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 6/3/2022 2:40:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[AccountId] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Descripion] [nvarchar](50) NOT NULL,
	[Rating] [nvarchar](50) NOT NULL,
	[Price] [nvarchar](50) NOT NULL,
	[JobType] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 6/3/2022 2:40:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[OrderId] [nchar](10) NOT NULL,
	[CustomerId] [nvarchar](50) NOT NULL,
	[EmployeId] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[PhoneNumber] [nchar](10) NOT NULL,
	[Price] [nchar](10) NOT NULL,
	[Description] [nchar](10) NOT NULL,
	[PaymentId] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Payment]    Script Date: 6/3/2022 2:40:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment](
	[PaymentId] [int] NOT NULL,
	[method] [nvarchar](50) NOT NULL,
	[tramsactionId] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[PaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Account] FOREIGN KEY([AccountId])
REFERENCES [dbo].[Account] ([Account_id])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Account]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Payment] FOREIGN KEY([PaymentId])
REFERENCES [dbo].[Payment] ([PaymentId])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Payment]
GO
USE [master]
GO
ALTER DATABASE [GreenGarden] SET  READ_WRITE 
GO
